### ISSUE TITLE
addon doesn't work anymore with kodi 19

### ISSUE THREAD

**Issue by gael-B** [elbowz/partymode-autostart-xbmc-service#11]
Hi,
I use and love the partymode autostart in Kodi !
I've just updated Kodi from version 18.9 to 19 (Matrix)

plugin is not working anymore (due to Python version 3 needed I think)

How to repair it ?

**Comment by TimmyP777** [comment]
Yup. Its dead. I cant believe Kodi doesnt have a native feature after 20 years to start a playlist upon entering... unreal. Please update if you can!

**Comment by elbowz** [comment]
Hi guys, the project is discontinued...

I'll try to port it to kodi 19, but I don't know when (weeks/months).

I'm sorry...i hope you understand

**Comment by TimmyP777** [comment]
Its fine. Thank you for your addon and I am perfectly happy sticking to 18.9. I personally think KODI has went too eliminating compatibility with all these addons. There is no reason this addon should be broken, let alone hundreds of others all of a sudden.

**Comment by outsideset** [comment]
I put together a preliminary pull request to update to python 3. All I did was bump the revisions and detailed here:
   https://forum.kodi.tv/showthread.php?tid=351745

I haven't tested it. I will see if I can figure out how to do that.

**Comment by outsideset** [comment]
ok I made a few more tweaks and its working, at least with the basic settings.
- you can download the code as a zipfile from my fork. That zip file can be installed using the add on manager.
- the icon doesn't display correctly

**Comment by TimmyP777** [comment]
Hey thanks! Looks like I have something to do tomorrow!

**Comment by TimmyP777** [comment]
It doesnt install. It says Python dependency 2.12.0 could not be met/

**Comment by outsideset** [comment]
Be sure you're downloading my fork of the repo, and dowloading the latest version

**Comment by TimmyP777** [comment]
Yeah its a total no go. Im on android if that helps.

You have to select a playlist from favorites, and have it play the favorite
since kodi has the ".kodi" name for its android data directory and
 the integrated kodi browser cannot browse to the playlist directory.
Copying the playlist to a place it can see and using the regular playlist
on startup (instead of favorite on startup) doesnt work either.

Thank you, but dont worry about it. Frankly I am so sick of this open
source crap from Kodi. Its a never complete program and I will stick to
18.9 for the next 5 years of my life. It even plays HDR\4k fine. So what is
the point? Thanks again.

Sorry for venting, its been 20 years and XBMC\Kodi has never been a
complete program ever.

**Comment by TimmyP777** [comment]
Btw. It was "1 or more items failed to play" everything installed fine, the
plugin worked, I saw the slightly different counting dialog so I know I had
your fork.

Everything worked until it loaded and finished the countdown. 1 or more
items failed to play.

For videos... btw. I dont know if you are fixing it for music or whatever,
but just in case its all strictly saved video playlists.

**Comment by elbowz** [comment]
The release for Kodi 19 should be ready (also thanks to @outsideset).
It is on master branch but not submitted to the official kodi repository yet...**it need some deep test**

Please, download from [https://github.com/elbowz/partymode-autostart-xbmc-service/archive/v0.9.2.zip](https://github.com/elbowz/partymode-autostart-xbmc-service/archive/v0.9.2.zip), install in Kodi 19 and test how much different settings you can

**Comment by TimmyP777** [comment]
Wow thank you both outsideset and elbowz. Ill test today in a couple hours.

**Comment by elbowz** [comment]
> Wow thank you both outsideset and elbowz. Ill test today in a couple hours.

Take your time, I'll not push in the official kodi matrix repo before a week :+1:

**Comment by gael-B** [comment]
> The release for Kodi 19 should be ready (also thanks to @outsideset).
> It is on master branch but not submitted to the official kodi repository yet...**it need some deep test**
> 
> Please, download from https://github.com/elbowz/partymode-autostart-xbmc-service/archive/v0.9.2.zip, install in Kodi 19 and test how much different settings you can

Thank you very much, I'll test it this evening

**Comment by outsideset** [comment]
Thanks @elbowz for moving this forward I will give it a look. Its been an essential part of my stereo setup for years so I very much appreciate it.

**Comment by TimmyP777** [comment]
Seems to work great. MAN those changes to SMB defaults made this a headache. Why even bother importing a library if the SMB client is a different default?

Anyways, THANK YOU.

Im on a Firestick 4k.  For video, you must make a playlist, add it to favorites, and configure the addon to play the favorite. IT WORKS AGAIN!

If you want me to test anything else lmk. I cant select a playlist in the options because they are hidden behind the .kodi userdata directory. (the . in .kodi makes it hidden just in case). Kodi, at least in 18.9 or less, cant browse to the userdata playlist folder because of this, so maybe in updating this addon give it the ability to browse the playlist directory (on Android).

Thanks again. This is great. The headaches are over! Thanks to both of you!

**Comment by elbowz** [comment]
I'm glad then someone enjoy and find useful this addon :)

Finally it was accepted in the Kodi matrix official repo: https://github.com/xbmc/repo-scripts/pull/1912

**Comment by gael-B** [comment]
Thank you very much for your support
